= Riding the Waves

Whether we are wearing robes or jeans, maintaining careful self-regard
means putting the emphasis in the right place. Whatever understanding we
have regarding the Buddha’s teachings, we will only integrate that
understanding into the rest of our lives if we manage to maintain faith
and confidence in the path and the practice.

When we start out on this journey we are energized by a sense of trust
that there is truth and it can be realized. This trust has as its
companion, interest: interest in finding out for ourselves how to let go
of that which limits us. And in every moment of letting go, faith,
confidence and trust deepen, becoming stronger, and our hearts open just
a little bit – or maybe a lot. Now we need to be asking ourselves, what
is it that will nourish and sustain this process in the long term? When
our hearts open, we see more and feel more, and we are also faced with
more questions. In the beginning it was fine to run on the energy of
inspiration, but as we progress, we find such a source of energy
unsustainable; new ways of supporting ourselves on this journey need to
be found.
